# Generated by Django 5.1.7 on 2025-04-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERID', models.CharField(help_text='USER_ID', max_length=20)),
                ('USERNAME', models.CharField(max_length=100)),
                ('MOVIENAME', models.CharField(max_length=100)),
                ('NOOFSEATS', models.IntegerField()),
                ('EMAIL', models.EmailField(max_length=254)),
            ],
        ),
    ]
